################################################################################################## 
## 28-FEB-2016 - This R Scripts contains two functions (makeCacheMatrix and
## cacheSolve) that demonstrates the use of the <<- operator 
## ***********************************************************************************************
## * function: makeCacheMatrix  
## * args: marix 
## * returns: list of fucntions
## ***********************************************************************************************
## * makeCacheMatrix is a function taking a matrix as argument and generates a list of functions: 
## *     set get setinvert getinvert                                                                       
## *                                                                                              
## *     set: defines a function that assignthe matrix                                            
## *     passed in argument to a variable set in the parent environment of                        
## *     makeCacheMatrix and reset the cache result                                               
## *                                                                                                      
## *     get: defines a function that returns the matrix passed in argument                               
## *
## *     setinvert:defines a function that assigns its argument to a variable set in
## *     the parent environment this variable is the cached value of the matrix invert
## *
## *     getinvert: defines a function that returns the cached value in setInvert
## ************************************************************************************************
## * function cacheSolve 
## * args: list defined by makeCacheMatrix, opt. arg of R solve() fucntion  
## * retuns: invert matrix
## ************************************************************************************************
## * function cacheSolve checks first if the invert of the matrix has been caclulated anc cached, 
## * if it is the case, the cached value is returned otherwise it is calculate and cached
## ************************************************************************************************
## NOTEs:  1. all matrix passed as arguments are considered inversible
##         2. You need to call makeCacheMatrix first before calling cacheSolve
## Example:
##      someMat <- matrix(runif(10000), ncol=100) 
##      myMat <- makeCacheMatrix(someMat)
##      cacheSolve(myMat)
###################################################################################################
## function makeCacheMatrix takes a matrix as an argument and returns a list of functions 


makeCacheMatrix <- function(m = matrix()) {
        r <- NULL
        set <- function(y) {
                m <<- y
                r <<- NULL
        }
        get <- function() m
        setinvert <- function(invert) r <<- invert
        getinvert <- function() r
        list(set = set, get = get,
             setinvert = setinvert,
             getinvert = getinvert)
}

## function cacheSolve takes a list 'x'  of functions (generated by makeCacheMatrix) and returns the invert 
## of the matrix stored when the list 'x'  was created
cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of the matrix assigned in 'x'
        r <- x$getinvert() 
        if(!is.null(r)) {
                message("getting cached data")
                return(r)
        }
        data <- x$get()
        r <- solve(data, ...)
        x$setinvert(r)
        r
}

